apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-service
  namespace: qbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-service-account
  namespace: qbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: deployment-service
  namespace: qbox
