apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services","deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-pod-readers
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: pod-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "6edd255b-ac11-4396-b4e9-5caea023b7d3"