trigger: none

variables:
  acrName: jakob
  acrResourceGroupName: acr
  aksPolicy: true
  controlPlaneSku: Free
  kubernetesVersion: 1.19.3
  subnetName: cluster
  subnetPrefix: 10.230.0.0/16
  vnetAddressPrefix: 10.0.0.0/8
  vnodesSubnetName: vnodes
  vnodesSubnetPrefix: 10.231.0.0/16
  workspaceName: ndclondon
  workspaceResourceGroup: ndclondon

pool:
  vmImage: 'windows-2019'

stages:

- stage: DevTestEU
  displayName: DevTestEU
  variables:
    clusterName: ndc-test
    location: westeurope
    namespacesFile: ./AKS/namespaces-devtest.yaml
    resourceGroup: ndc-test
    vnetName: ndc-test
    vnetResourceGroupName: ndc-test

  jobs:      
  - template: deploy-template.yml