trigger: none

variables:
  acrName: jakob
  acrResourceGroupName: acr
  aksPolicy: true
  controlPlaneSku: Free
  kubernetesVersion: 1.19.3
  namespace: qbox  
  subnetName: cluster
  subnetPrefix: 10.230.0.0/16
  vnetAddressPrefix: 10.0.0.0/8
  vnodesSubnetName: vnodes
  vnodesSubnetPrefix: 10.231.0.0/16
  workspaceName: ndclondon
  workspaceResourceGroup: ndclondon

pool:
  vmImage: 'windows-2019'

stages:

- stage: DevTest
  displayName: DevTest
  variables:
    clusterName: ndc-test
    location: westeurope
    resourceGroup: ndc-test
    vnetName: ndc-test
    vnetResourceGroupName: ndc-test
  jobs:      
  - template: deploy-template.yml
    parameters:
        environment: Development  

- stage: ProdEU
  displayName: ProdEU
  dependsOn: DevTest
  variables:
    clusterName: ndc-prodeu
    location: westeurope
    resourceGroup: ndc-prodeu
    vnetName: ndc-prodeu
    vnetResourceGroupName: ndc-prodeu
  jobs:      
  - template: deploy-template.yml
    parameters:
        environment: ProdEU

- stage: ProdUS
  displayName: ProdUS
  dependsOn: DevTest
  variables:
    clusterName: ndc-produs
    location: eastus2
    resourceGroup: ndc-produs
    vnetName: ndc-produs
    vnetResourceGroupName: ndc-produs
  jobs:      
  - template: deploy-template.yml
    parameters:
        environment: ProdUS