azureAuthentication:
  appId: c02b6d45-c92d-4da3-9bef-5aff601d3bf7
  appKey: eea00d02-f34f-4699-9d21-d1fad3a9c6ad

azureMetadata:
  tenantId: 7910c4f6-7843-49ce-b9de-dc9d4379f950
  subscriptionId: b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5
  resourceGroupName: tdswe-test
metricDefaults:
  aggregation:
    interval: 00:00:30
  scraping:
    schedule: "* * * * *"